server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/users {
        proxy_pass http://user-service:5000;
    }

    location /api/restaurants {
        proxy_pass http://restaurant-service:5000;
    }

    location /api/orders {
        proxy_pass http://order-service:5000;
    }
}
