name: Build and Push user-service

on:
  push:
    branches: [main]
    paths:
      - "user-service/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set tag
        id: vars
        run: echo "tag=dev-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./user-service
          push: true
          tags: pavanreddy8/foodapp-user-service:${{ steps.vars.outputs.tag }}
      - name: Update dev overlay in foodapp-gitops
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_REPO_TOKEN }}@github.com/Pavan-7673/foodapp-gitops.git
          cd foodapp-gitops/apps/user-service/overlays/dev
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          ./kustomize edit set image pavanreddy8/foodapp-user-service=pavanreddy8/foodapp-user-service:${{ steps.vars.outputs.tag }}
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "ci: bump user-service dev to ${{ steps.vars.outputs.tag }}"
          git push
